include: package:leancode_lint/analysis_options.yaml

formatter:
  trailing_commas: preserve

analyzer:
  plugins:
    - custom_lint
  exclude:
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - lib/l10n/*
