arb-dir: lib/resources/translations/l10n
template-arb-file: app_en.arb
output-localization-file: app_localizations.dart
nullable-getter: false
poeditor-project-id: 809786
preferred-supported-locales: [ en ]
