arb-dir: lib/l10n
template-arb-file: app_pl.arb
output-localization-file: app_localizations.dart
synthetic-package: false
nullable-getter: false
poeditor-project-id: 809786
preferred-supported-locales: [ en ]
